//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MreServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegulacionExtranjerosModel", Namespace="http://schemas.datacontract.org/2004/07/MRE.ConsultaOrdenCedulacion.Model")]
    public partial class RegulacionExtranjerosModel : object
    {
        
        private string CiudadField;
        
        private int CodigoField;
        
        private int CodigoRegistroField;
        
        private string CorreoElectronicoField;
        
        private string DetalleField;
        
        private string DireccionEcuadorField;
        
        private string DiscapacidadSiNoField;
        
        private string DobleNacionalidadSiNoField;
        
        private string DocumentoIdentidadSiNoField;
        
        private string EstadoCivilField;
        
        private System.DateTime FechaEmisionDocumentoField;
        
        private System.Nullable<System.DateTime> FechaEmisionVisaField;
        
        private System.DateTime FechaExpiracionDocumentoField;
        
        private System.Nullable<System.DateTime> FechaExpiracionVisaField;
        
        private System.DateTime FechaIngresoPaisField;
        
        private System.DateTime FechaNacimientoField;
        
        private byte[] FotoGrafiaField;
        
        private string GeneroField;
        
        private string HijosSiNoField;
        
        private byte[] HuellasDactilaresField;
        
        private string NacionalidadField;
        
        private string NivelEducativoField;
        
        private string NombresField;
        
        private string NumRegistroPermanenciaField;
        
        private string NumeroCarnetDiscapacidadField;
        
        private string NumeroDocumentoField;
        
        private string NumeroVisaField;
        
        private string OcupacionField;
        
        private string PaisEmisionField;
        
        private string PaisNacimientoField;
        
        private string PaisResidenciaPreviaField;
        
        private string PrimerApellidoField;
        
        private string ProfesionField;
        
        private string ProvinciaField;
        
        private string PuntoIngresoEcuadorField;
        
        private string PuntoIngresoRegularSiNoField;
        
        private string SegundoApellidoField;
        
        private string SeleccioneOtraNacionalidadField;
        
        private string TelefonoField;
        
        private string TiempoEcuadorField;
        
        private string TipoDocumentoField;
        
        private string TipoResidenciaEcuadorField;
        
        private string TipoVisaField;
        
        private string VisaIndividualFamiliarField;
        
        private string VisaSiNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad
        {
            get
            {
                return this.CiudadField;
            }
            set
            {
                this.CiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRegistro
        {
            get
            {
                return this.CodigoRegistroField;
            }
            set
            {
                this.CodigoRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico
        {
            get
            {
                return this.CorreoElectronicoField;
            }
            set
            {
                this.CorreoElectronicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalle
        {
            get
            {
                return this.DetalleField;
            }
            set
            {
                this.DetalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionEcuador
        {
            get
            {
                return this.DireccionEcuadorField;
            }
            set
            {
                this.DireccionEcuadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscapacidadSiNo
        {
            get
            {
                return this.DiscapacidadSiNoField;
            }
            set
            {
                this.DiscapacidadSiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DobleNacionalidadSiNo
        {
            get
            {
                return this.DobleNacionalidadSiNoField;
            }
            set
            {
                this.DobleNacionalidadSiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentoIdentidadSiNo
        {
            get
            {
                return this.DocumentoIdentidadSiNoField;
            }
            set
            {
                this.DocumentoIdentidadSiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCivil
        {
            get
            {
                return this.EstadoCivilField;
            }
            set
            {
                this.EstadoCivilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEmisionDocumento
        {
            get
            {
                return this.FechaEmisionDocumentoField;
            }
            set
            {
                this.FechaEmisionDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaEmisionVisa
        {
            get
            {
                return this.FechaEmisionVisaField;
            }
            set
            {
                this.FechaEmisionVisaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaExpiracionDocumento
        {
            get
            {
                return this.FechaExpiracionDocumentoField;
            }
            set
            {
                this.FechaExpiracionDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaExpiracionVisa
        {
            get
            {
                return this.FechaExpiracionVisaField;
            }
            set
            {
                this.FechaExpiracionVisaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaIngresoPais
        {
            get
            {
                return this.FechaIngresoPaisField;
            }
            set
            {
                this.FechaIngresoPaisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FotoGrafia
        {
            get
            {
                return this.FotoGrafiaField;
            }
            set
            {
                this.FotoGrafiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genero
        {
            get
            {
                return this.GeneroField;
            }
            set
            {
                this.GeneroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HijosSiNo
        {
            get
            {
                return this.HijosSiNoField;
            }
            set
            {
                this.HijosSiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] HuellasDactilares
        {
            get
            {
                return this.HuellasDactilaresField;
            }
            set
            {
                this.HuellasDactilaresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nacionalidad
        {
            get
            {
                return this.NacionalidadField;
            }
            set
            {
                this.NacionalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NivelEducativo
        {
            get
            {
                return this.NivelEducativoField;
            }
            set
            {
                this.NivelEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumRegistroPermanencia
        {
            get
            {
                return this.NumRegistroPermanenciaField;
            }
            set
            {
                this.NumRegistroPermanenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCarnetDiscapacidad
        {
            get
            {
                return this.NumeroCarnetDiscapacidadField;
            }
            set
            {
                this.NumeroCarnetDiscapacidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento
        {
            get
            {
                return this.NumeroDocumentoField;
            }
            set
            {
                this.NumeroDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroVisa
        {
            get
            {
                return this.NumeroVisaField;
            }
            set
            {
                this.NumeroVisaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ocupacion
        {
            get
            {
                return this.OcupacionField;
            }
            set
            {
                this.OcupacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaisEmision
        {
            get
            {
                return this.PaisEmisionField;
            }
            set
            {
                this.PaisEmisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaisNacimiento
        {
            get
            {
                return this.PaisNacimientoField;
            }
            set
            {
                this.PaisNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaisResidenciaPrevia
        {
            get
            {
                return this.PaisResidenciaPreviaField;
            }
            set
            {
                this.PaisResidenciaPreviaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Profesion
        {
            get
            {
                return this.ProfesionField;
            }
            set
            {
                this.ProfesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PuntoIngresoEcuador
        {
            get
            {
                return this.PuntoIngresoEcuadorField;
            }
            set
            {
                this.PuntoIngresoEcuadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PuntoIngresoRegularSiNo
        {
            get
            {
                return this.PuntoIngresoRegularSiNoField;
            }
            set
            {
                this.PuntoIngresoRegularSiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeleccioneOtraNacionalidad
        {
            get
            {
                return this.SeleccioneOtraNacionalidadField;
            }
            set
            {
                this.SeleccioneOtraNacionalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TiempoEcuador
        {
            get
            {
                return this.TiempoEcuadorField;
            }
            set
            {
                this.TiempoEcuadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento
        {
            get
            {
                return this.TipoDocumentoField;
            }
            set
            {
                this.TipoDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoResidenciaEcuador
        {
            get
            {
                return this.TipoResidenciaEcuadorField;
            }
            set
            {
                this.TipoResidenciaEcuadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoVisa
        {
            get
            {
                return this.TipoVisaField;
            }
            set
            {
                this.TipoVisaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisaIndividualFamiliar
        {
            get
            {
                return this.VisaIndividualFamiliarField;
            }
            set
            {
                this.VisaIndividualFamiliarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisaSiNo
        {
            get
            {
                return this.VisaSiNoField;
            }
            set
            {
                this.VisaSiNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PuntoEntradaModel", Namespace="http://schemas.datacontract.org/2004/07/MRE.ConsultaOrdenCedulacion.Model")]
    public partial class PuntoEntradaModel : object
    {
        
        private int CodigoField;
        
        private string DetalleField;
        
        private string PuntoIngresoEcuadorField;
        
        private string PuntoIngresoRegularSiNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalle
        {
            get
            {
                return this.DetalleField;
            }
            set
            {
                this.DetalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PuntoIngresoEcuador
        {
            get
            {
                return this.PuntoIngresoEcuadorField;
            }
            set
            {
                this.PuntoIngresoEcuadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PuntoIngresoRegularSiNo
        {
            get
            {
                return this.PuntoIngresoRegularSiNoField;
            }
            set
            {
                this.PuntoIngresoRegularSiNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlujoMigratorioDatos", Namespace="http://schemas.datacontract.org/2004/07/MRE.ConsultaOrdenCedulacion.Model")]
    public partial class FlujoMigratorioDatos : object
    {
        
        private int CodigoField;
        
        private string DetalleField;
        
        private MreServiceReference.FlujoMigratorioMovimientoModel[] ListaMovimientoMigratorioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalle
        {
            get
            {
                return this.DetalleField;
            }
            set
            {
                this.DetalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MreServiceReference.FlujoMigratorioMovimientoModel[] ListaMovimientoMigratorio
        {
            get
            {
                return this.ListaMovimientoMigratorioField;
            }
            set
            {
                this.ListaMovimientoMigratorioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlujoMigratorioMovimientoModel", Namespace="http://schemas.datacontract.org/2004/07/MRE.ConsultaOrdenCedulacion.Model")]
    public partial class FlujoMigratorioMovimientoModel : object
    {
        
        private string ApellidosNombresField;
        
        private string CategoriaMigratoriaField;
        
        private int CodigoErrorField;
        
        private string FechaHoraMovimientoField;
        
        private string FechaNacimientoField;
        
        private string GeneroField;
        
        private string MedioField;
        
        private string MotivoViajeField;
        
        private string NacionalidadDocumentoMovMigraField;
        
        private string NumeroDocumentoMovMigraField;
        
        private string PaisDestinoField;
        
        private string PaisNacimientoField;
        
        private string PaisOrigenField;
        
        private string PaisResidenciaField;
        
        private string PuertoRegistroField;
        
        private string TarjetaAndinaField;
        
        private string TiempoDeclaradoField;
        
        private string TipoDocumentoMovMigraField;
        
        private string TipoMovimientoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidosNombres
        {
            get
            {
                return this.ApellidosNombresField;
            }
            set
            {
                this.ApellidosNombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaMigratoria
        {
            get
            {
                return this.CategoriaMigratoriaField;
            }
            set
            {
                this.CategoriaMigratoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoError
        {
            get
            {
                return this.CodigoErrorField;
            }
            set
            {
                this.CodigoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaHoraMovimiento
        {
            get
            {
                return this.FechaHoraMovimientoField;
            }
            set
            {
                this.FechaHoraMovimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genero
        {
            get
            {
                return this.GeneroField;
            }
            set
            {
                this.GeneroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Medio
        {
            get
            {
                return this.MedioField;
            }
            set
            {
                this.MedioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoViaje
        {
            get
            {
                return this.MotivoViajeField;
            }
            set
            {
                this.MotivoViajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NacionalidadDocumentoMovMigra
        {
            get
            {
                return this.NacionalidadDocumentoMovMigraField;
            }
            set
            {
                this.NacionalidadDocumentoMovMigraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumentoMovMigra
        {
            get
            {
                return this.NumeroDocumentoMovMigraField;
            }
            set
            {
                this.NumeroDocumentoMovMigraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaisDestino
        {
            get
            {
                return this.PaisDestinoField;
            }
            set
            {
                this.PaisDestinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaisNacimiento
        {
            get
            {
                return this.PaisNacimientoField;
            }
            set
            {
                this.PaisNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaisOrigen
        {
            get
            {
                return this.PaisOrigenField;
            }
            set
            {
                this.PaisOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaisResidencia
        {
            get
            {
                return this.PaisResidenciaField;
            }
            set
            {
                this.PaisResidenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PuertoRegistro
        {
            get
            {
                return this.PuertoRegistroField;
            }
            set
            {
                this.PuertoRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TarjetaAndina
        {
            get
            {
                return this.TarjetaAndinaField;
            }
            set
            {
                this.TarjetaAndinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TiempoDeclarado
        {
            get
            {
                return this.TiempoDeclaradoField;
            }
            set
            {
                this.TiempoDeclaradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumentoMovMigra
        {
            get
            {
                return this.TipoDocumentoMovMigraField;
            }
            set
            {
                this.TipoDocumentoMovMigraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMovimiento
        {
            get
            {
                return this.TipoMovimientoField;
            }
            set
            {
                this.TipoMovimientoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultasModel", Namespace="http://schemas.datacontract.org/2004/07/MRE.ConsultaOrdenCedulacion.Model")]
    public partial class MultasModel : object
    {
        
        private int CodigoField;
        
        private string DetalleField;
        
        private MreServiceReference.MultasNotificacionesModel DetalleMulasNotificacionesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalle
        {
            get
            {
                return this.DetalleField;
            }
            set
            {
                this.DetalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MreServiceReference.MultasNotificacionesModel DetalleMulasNotificaciones
        {
            get
            {
                return this.DetalleMulasNotificacionesField;
            }
            set
            {
                this.DetalleMulasNotificacionesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultasNotificacionesModel", Namespace="http://schemas.datacontract.org/2004/07/MRE.ConsultaOrdenCedulacion.Model")]
    public partial class MultasNotificacionesModel : object
    {
        
        private string ApellidosNombresField;
        
        private int CodigoErrorField;
        
        private string FechaNacimientoField;
        
        private string GeneroField;
        
        private MreServiceReference.MultasFlujoMigratorioModel[] ListaMultasField;
        
        private MreServiceReference.NotificacionesSalidaVoluntarias[] ListaNotificacionesSalidasField;
        
        private string PaisNacimientoField;
        
        private string PaisResidenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidosNombres
        {
            get
            {
                return this.ApellidosNombresField;
            }
            set
            {
                this.ApellidosNombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoError
        {
            get
            {
                return this.CodigoErrorField;
            }
            set
            {
                this.CodigoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genero
        {
            get
            {
                return this.GeneroField;
            }
            set
            {
                this.GeneroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MreServiceReference.MultasFlujoMigratorioModel[] ListaMultas
        {
            get
            {
                return this.ListaMultasField;
            }
            set
            {
                this.ListaMultasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MreServiceReference.NotificacionesSalidaVoluntarias[] ListaNotificacionesSalidas
        {
            get
            {
                return this.ListaNotificacionesSalidasField;
            }
            set
            {
                this.ListaNotificacionesSalidasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaisNacimiento
        {
            get
            {
                return this.PaisNacimientoField;
            }
            set
            {
                this.PaisNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaisResidencia
        {
            get
            {
                return this.PaisResidenciaField;
            }
            set
            {
                this.PaisResidenciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultasFlujoMigratorioModel", Namespace="http://schemas.datacontract.org/2004/07/MRE.ConsultaOrdenCedulacion.Model")]
    public partial class MultasFlujoMigratorioModel : object
    {
        
        private int CodigoErrorField;
        
        private string EstadoField;
        
        private string FechaRegistroField;
        
        private string TipoMultaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoError
        {
            get
            {
                return this.CodigoErrorField;
            }
            set
            {
                this.CodigoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMulta
        {
            get
            {
                return this.TipoMultaField;
            }
            set
            {
                this.TipoMultaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificacionesSalidaVoluntarias", Namespace="http://schemas.datacontract.org/2004/07/MRE.ConsultaOrdenCedulacion.Model")]
    public partial class NotificacionesSalidaVoluntarias : object
    {
        
        private int CodigoErrorField;
        
        private string EstadoField;
        
        private string FechaRegistroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoError
        {
            get
            {
                return this.CodigoErrorField;
            }
            set
            {
                this.CodigoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComprobanteBanEcuadorModel", Namespace="http://schemas.datacontract.org/2004/07/MRE.ConsultaOrdenCedulacion.Model")]
    public partial class ComprobanteBanEcuadorModel : object
    {
        
        private int CodigoBanEcuadorField;
        
        private string CuentaField;
        
        private string FechaField;
        
        private string MensajeBanEcuadorField;
        
        private string NumeroComprobanteField;
        
        private string OficinaField;
        
        private string ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoBanEcuador
        {
            get
            {
                return this.CodigoBanEcuadorField;
            }
            set
            {
                this.CodigoBanEcuadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuenta
        {
            get
            {
                return this.CuentaField;
            }
            set
            {
                this.CuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeBanEcuador
        {
            get
            {
                return this.MensajeBanEcuadorField;
            }
            set
            {
                this.MensajeBanEcuadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroComprobante
        {
            get
            {
                return this.NumeroComprobanteField;
            }
            set
            {
                this.NumeroComprobanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Oficina
        {
            get
            {
                return this.OficinaField;
            }
            set
            {
                this.OficinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiscapacidadModel", Namespace="http://schemas.datacontract.org/2004/07/MRE.ConsultaOrdenCedulacion.Model")]
    public partial class DiscapacidadModel : object
    {
        
        private string ApellidosField;
        
        private string CedulaField;
        
        private int CodigoField;
        
        private string CodigoConadisField;
        
        private string GradoDiscapacidadField;
        
        private string MensajeField;
        
        private string NombresField;
        
        private string PorcentajeDiscapacidadField;
        
        private string TipoDiscapacidadPredominaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos
        {
            get
            {
                return this.ApellidosField;
            }
            set
            {
                this.ApellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula
        {
            get
            {
                return this.CedulaField;
            }
            set
            {
                this.CedulaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoConadis
        {
            get
            {
                return this.CodigoConadisField;
            }
            set
            {
                this.CodigoConadisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradoDiscapacidad
        {
            get
            {
                return this.GradoDiscapacidadField;
            }
            set
            {
                this.GradoDiscapacidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PorcentajeDiscapacidad
        {
            get
            {
                return this.PorcentajeDiscapacidadField;
            }
            set
            {
                this.PorcentajeDiscapacidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDiscapacidadPredomina
        {
            get
            {
                return this.TipoDiscapacidadPredominaField;
            }
            set
            {
                this.TipoDiscapacidadPredominaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceRegulacionExtranjeros")]
    public interface IServiceRegulacionExtranjeros
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRegulacionExtranjeros/ConsultaRegulacionExtranjeros", ReplyAction="http://tempuri.org/IServiceRegulacionExtranjeros/ConsultaRegulacionExtranjerosRes" +
            "ponse")]
        System.Threading.Tasks.Task<MreServiceReference.RegulacionExtranjerosModel> ConsultaRegulacionExtranjerosAsync(int codigoRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRegulacionExtranjeros/ConsultaPuntoControl", ReplyAction="http://tempuri.org/IServiceRegulacionExtranjeros/ConsultaPuntoControlResponse")]
        System.Threading.Tasks.Task<MreServiceReference.PuntoEntradaModel> ConsultaPuntoControlAsync(int codigoRegistro, System.DateTime fechaControlInicial, System.DateTime fechaControlFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRegulacionExtranjeros/Consulta_F_M_RegulacionExtranjer" +
            "os", ReplyAction="http://tempuri.org/IServiceRegulacionExtranjeros/Consulta_F_M_RegulacionExtranjer" +
            "osResponse")]
        System.Threading.Tasks.Task<MreServiceReference.FlujoMigratorioDatos> Consulta_F_M_RegulacionExtranjerosAsync(int codigoRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRegulacionExtranjeros/Consulta_Multas_RegulacionExtran" +
            "jeros", ReplyAction="http://tempuri.org/IServiceRegulacionExtranjeros/Consulta_Multas_RegulacionExtran" +
            "jerosResponse")]
        System.Threading.Tasks.Task<MreServiceReference.MultasModel> Consulta_Multas_RegulacionExtranjerosAsync(int codigoRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRegulacionExtranjeros/ConsultaPago", ReplyAction="http://tempuri.org/IServiceRegulacionExtranjeros/ConsultaPagoResponse")]
        System.Threading.Tasks.Task<MreServiceReference.ComprobanteBanEcuadorModel> ConsultaPagoAsync(string numeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRegulacionExtranjeros/ConsultaDiscapacidadmsp", ReplyAction="http://tempuri.org/IServiceRegulacionExtranjeros/ConsultaDiscapacidadmspResponse")]
        System.Threading.Tasks.Task<MreServiceReference.DiscapacidadModel> ConsultaDiscapacidadmspAsync(string numeroCedula);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IServiceRegulacionExtranjerosChannel : MreServiceReference.IServiceRegulacionExtranjeros, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class ServiceRegulacionExtranjerosClient : System.ServiceModel.ClientBase<MreServiceReference.IServiceRegulacionExtranjeros>, MreServiceReference.IServiceRegulacionExtranjeros
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceRegulacionExtranjerosClient() : 
                base(ServiceRegulacionExtranjerosClient.GetDefaultBinding(), ServiceRegulacionExtranjerosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceRegulacionExtranjeros.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceRegulacionExtranjerosClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceRegulacionExtranjerosClient.GetBindingForEndpoint(endpointConfiguration), ServiceRegulacionExtranjerosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceRegulacionExtranjerosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceRegulacionExtranjerosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceRegulacionExtranjerosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceRegulacionExtranjerosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceRegulacionExtranjerosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<MreServiceReference.RegulacionExtranjerosModel> ConsultaRegulacionExtranjerosAsync(int codigoRegistro)
        {
            return base.Channel.ConsultaRegulacionExtranjerosAsync(codigoRegistro);
        }
        
        public System.Threading.Tasks.Task<MreServiceReference.PuntoEntradaModel> ConsultaPuntoControlAsync(int codigoRegistro, System.DateTime fechaControlInicial, System.DateTime fechaControlFinal)
        {
            return base.Channel.ConsultaPuntoControlAsync(codigoRegistro, fechaControlInicial, fechaControlFinal);
        }
        
        public System.Threading.Tasks.Task<MreServiceReference.FlujoMigratorioDatos> Consulta_F_M_RegulacionExtranjerosAsync(int codigoRegistro)
        {
            return base.Channel.Consulta_F_M_RegulacionExtranjerosAsync(codigoRegistro);
        }
        
        public System.Threading.Tasks.Task<MreServiceReference.MultasModel> Consulta_Multas_RegulacionExtranjerosAsync(int codigoRegistro)
        {
            return base.Channel.Consulta_Multas_RegulacionExtranjerosAsync(codigoRegistro);
        }
        
        public System.Threading.Tasks.Task<MreServiceReference.ComprobanteBanEcuadorModel> ConsultaPagoAsync(string numeroDocumento)
        {
            return base.Channel.ConsultaPagoAsync(numeroDocumento);
        }
        
        public System.Threading.Tasks.Task<MreServiceReference.DiscapacidadModel> ConsultaDiscapacidadmspAsync(string numeroCedula)
        {
            return base.Channel.ConsultaDiscapacidadmspAsync(numeroCedula);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceRegulacionExtranjeros))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceRegulacionExtranjeros))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.8.43/ConsultaServiciosMreWs/ServiceRegulacionExtranjeros.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceRegulacionExtranjerosClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceRegulacionExtranjeros);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceRegulacionExtranjerosClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceRegulacionExtranjeros);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceRegulacionExtranjeros,
        }
    }
}
